LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := dispctl.c
LOCAL_MODULE := dispctl
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := dispctl.c
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE := static_dispctl
LOCAL_MODULE_STEM := dispctl
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_STATIC_LIBRARIES := libc
include $(BUILD_EXECUTABLE)
